language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: 7
        - php: hhvm

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source

script: vendor/bin/tester -s -p php -c ./tests/php-unix.ini ./tests/HostBoxTests/
